### ISSUE TITLE
Task List: @milosmns

### ISSUE THREAD

**Issue by milosmns** [milosmns/contacts-generator-android#1]
- [x] Stats disappear when interrupted
- [x] Stats is empty
- [x] _Stop service on "home" pressed_
- [x] _Delete options (all and just generate)_
- [x] Rate URL
- [x] About dialog + more info
- [x] Notification for the service

**Comment by milosmns** [comment]
Stats now appear even when interrupted
Stats are now not empty
-- Stop service on "home" pressed -> invalid. Stats will appear again when you come back

**Comment by milosmns** [comment]
- Delete options are moved to the next milestone

**Comment by milosmns** [comment]
Using as task list now..
