### ISSUE TITLE
Task List: @milos192

### ISSUE THREAD

**Issue by milosmns** [milosmns/contacts-generator-android#2]
- [x] Stats UI 
- [x] Handle multiple activity instances for "main" activity
- [x] _Progress should show 134/420 etc_
- [x] _Progress should show 28% indicator_
- [x] _Progress STOP button should be red with white text instead of gray_
- [x] _Save "last selected number", "last selected gender", "last 'use photos' value"_
- [x] _Handle "delete" dialog, we won't offer "STOP" for that operation in the first release_

**Comment by milosmns** [comment]
>> Handle "delete" dialog, we won't offer "STOP" for that operation in the first release << - moved to the next milestone

**Comment by milosmns** [comment]
Using task list now..

**Comment by milosmns** [comment]
Delete functionality added, closing this mega-task.
